name: CI
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/demo

    steps:
      - uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'

      - name: Build with maven
        run: ./mvnw -B clean verify --no-transfer-progress
